---
name: IO-Ppoll
version: 0.06
author:
  - 'Paul Evans E<lt>leonerd@leonerd.org.ukE<gt>'
abstract: Object interface to Linux's C<ppoll()> call
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Module::Build: 0
  Module::Build::Compat: 0
  Test::More: 0
provides:
  IO::Ppoll:
    file: lib/IO/Ppoll.pm
    version: 0.06
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
