---
name: IO-Ppoll
version: 0.09
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
abstract: Object interface to Linux's C<ppoll()> call
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Module::Build: 0
  Module::Build::Compat: 0
  Test::More: 0
provides:
  IO::Ppoll:
    file: lib/IO/Ppoll.pm
    version: 0.09
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
